### ISSUE TITLE
allow custom headers

### ISSUE THREAD

**Issue by yomed** [IonicaBizau/tinyreq#12]
Hi, would you consider allowing custom headers to be passed in for the request? I see they aren't being used - https://github.com/IonicaBizau/tinyreq/blob/master/lib/index.js#L50 (except for `content-length`). I would like to be able to set a user agent in `scrape-it`.

**Comment by IonicaBizau** [comment]
By default it's an empty object. Pass the `headers` option as an object containing the header name and value.

Example: https://github.com/IonicaBizau/scrape-it/issues/25#issuecomment-220277357

**Comment by yomed** [comment]
Thanks for the quick reply! It might be useful to document this functionality more clearly.

**Comment by IonicaBizau** [comment]
@yomed True. If you like, add here a new example: https://github.com/IonicaBizau/tinyreq/blob/master/example/index.js
