### ISSUE TITLE
using tinyreq with promises

### ISSUE THREAD

**Issue by hillscottc** [IonicaBizau/tinyreq#26]
Following the docs, I have no problem running the example using callbacks.
But the example as listed using a promises syntax gives no output.

    // Make a request with custom headers using a promise
    tinyreq({
        url: "http://example.com/"
      , headers: {
            "user-agent": "Crawler/1.0"
        }
    }).then(body => {
        console.log(body);
    }).catch(err => {
        console.log(err);
    });
I am using node version 8.3.0. What am I doing wrong?

**Comment by hillscottc** [comment]
Ah, answering my own question. I need to install Promise in my package.js
    
    $ npm install -S promise

Then it works fine.

**Comment by IonicaBizau** [comment]
What Node version?

**Comment by hillscottc** [comment]
I am using node version 8.3.0.

**Comment by IonicaBizau** [comment]
I'll check soon. Hmm... I remember it did work for me.

I'll try Node 8.3.0.

**Comment by hillscottc** [comment]
Thanks! :)

**Comment by IonicaBizau** [comment]
Yes, it was a bug! Thanks for the report! 🍰

**Comment by hillscottc** [comment]
Wow! Thanks for looking at this! Works great now.
Thanks!
