### ISSUE TITLE
proxy

### ISSUE THREAD

**Issue by GlauberF** [IonicaBizau/tinyreq#34]
how can I use proxy in the requests, changing the origin of the request.
I use the library: https://github.com/chimurai/http-proxy-middleware

I'm using your library (https://github.com/IonicaBizau/scrape-it), I tried to do it that way.

```scrapeIt ("url_I want_to_scrape", proxy({target: 'url_with_proxy', changeOrigin: true}), cb)```

**Comment by IonicaBizau** [comment]
Duplicate of https://github.com/IonicaBizau/scrape-it/issues/82
